### ISSUE TITLE
Please Provide Documentation/Make Example More Accessible

### ISSUE THREAD

**Issue by machineghost** [feathersjs/feathers-swagger#11]
Two requests:

1) Could you please provide documentation on how to use `feathers-swagger`?  The instructions listed on the GitHub page are rather deficient (eg. they don't mention the example.html file, or anything about the public directory at all, but having a publicly-served example.htm file is critical to actually being able seeing the generated documentation)

2) Could you please replace the Bower references on the example file with CDN versions?  This would make it so that anyone could use example.htm "out of the box" instead of having to setup an entire client side environment (with Bower, jQuery, Backbone, Handlebars, etc.).

... or better yet, if you could provide a "base HTML file" that anyone could use to get (even an extremely basic) UI "out of the box", that would be really great.  In fact, anything at all you can do to make it so that users can:

1) npm install feathers-swagger
2) add documentation to their feathers server/service
3) not have to do anything else 
4) see web-based documentation of their server/service

that would be awesome.

**Comment by daffl** [comment]
We would be happy about any contributions if you are interested in helping to maintain this plugin. This module hasn't been updated in three years and is not actively maintained at the moment. There are plans to bring it up to date eventually but the core team only has very limited resources available so any contributions will help to make it happen sooner.

**Comment by machineghost** [comment]
> This module hasn't been updated in three years and is not actively maintained at the moment.
Ah, I didn't realize.  Thanks.

You might want to consider putting that on the project's GitHub front page; no point in misleading people in to using an inactive library.
