### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pinussilvestrus** [feathersjs/feathers-swagger#19]
Hi,

after your latest commit last night, feathers-swagger fails to run in my project:

![image](https://cloud.githubusercontent.com/assets/9433996/20516561/4ef60422-b097-11e6-84bc-e3d964dc9e40.png)

Is there anything new required since the last commit?

regards.

**Comment by daffl** [comment]
Use the latest [version 0.3.0 from npm](https://www.npmjs.com/package/feathers-swagger). You may have to change `new feathersSwagger.utils.*` to `feathersSwagger.*` like `new feathersSwagger.utils.Definition()` to `feathersSwagger.definition()`.
