### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by khwerhahn** [feathersjs/feathers-swagger#31]
I get the following error message: `error: (ENOENT) Route: /docs/ - ENOENT: no such file or directory, stat '/usr/src/app/src/docs.html'`

In my `app.js` I have put:

```
.configure(swagger({
    docsPath: '/docs',
    uiIndex: path.join(__dirname, 'docs.html'),
    info: {
      title: 'A test',
      description: 'A description'
    }
  }))
```

The feathers app runs in a docker container. I guess it has something to do with creating the `docs.html` within the container. When I remove the `uiIndex:`, I get the swagger json output under `/docs/`.

**Comment by daffl** [comment]
You have to create a `docs.html` as shown in the [Readme](https://github.com/feathersjs/feathers-swagger#example-with-ui) and the [example](https://github.com/feathersjs/feathers-swagger/tree/master/example/simple).

**Comment by khwerhahn** [comment]
Thanks for the help. Just created a docs.html in the 'src' directory. Docker copies everything.
