### ISSUE TITLE
can i use custom swagger-ui?

### ISSUE THREAD

**Issue by davigmacode** [feathersjs/feathers-swagger#32]
Hi, can i use custom swagger-ui like on https://github.com/jensoleg/swagger-ui ?
It has better ui than the default

**Comment by daffl** [comment]
Yes. Any Swagger compatible UI pointing to `docsPath` (default `/docs`) will work. We could make the `require.resolve('swagger-ui')` in https://github.com/feathersjs/feathers-swagger/blob/master/src/index.js#L57 configurable (`config.uiPackage` defaulting to `swagger-ui`) so it could work the same as using the default UI.
Pull request welcome!

**Comment by davigmacode** [comment]
I'm sorry, i just end up serving static doc using [flatdoc](http://ricostacruz.com/flatdoc), 
i realize it more fast to write the doc using markdown than learning the swagger format

**Comment by daffl** [comment]
We'll leave it at that then.

**Comment by JigSawFr** [comment]
Could be great to make it configurable to use this Swagger explorer instead of default swagger ui !
