### ISSUE TITLE
Use default swagger-ui?

### ISSUE THREAD

**Issue by sinedied** [feathersjs/feathers-swagger#38]
It would be nice to also allow using the default `index.html` provided with `swagger-ui` instead of having to always provide our own, what do you think?

A property `ui: true` could be used, or a special value for the `uiIndex` property like `uiIndex: 'default'.

**Comment by daffl** [comment]
We could ship the default docs html (https://github.com/feathersjs/feathers-swagger/blob/master/example/simple/docs.html) and use that as the fallback if `uiIndex: true` (instead of the path).

**Comment by sinedied** [comment]
That would be great!

**Comment by daffl** [comment]
Pull request welcome 😄
