### ISSUE TITLE
Definition for prefixed routes

### ISSUE THREAD

**Issue by sinedied** [feathersjs/feathers-swagger#39]
All my services are versioned and available under the `/api/{version}/` prefix.

I'm trying to create definition for my services, but they all end up in the `api` swagger group, is there a way to prevent this?

**Comment by daffl** [comment]
Not at the moment I think. One fix would be to add a `config.prefix` and then in https://github.com/feathersjs/feathers-swagger/blob/master/src/index.js#L65 set something like `path = `${config.prefix}/${path}`

**Comment by sinedied** [comment]
At least do you know if it's possible to override the api group during the definition settings? That would be an acceptable workaround.

**Comment by daffl** [comment]
Why not a pull request that adds what I suggested?

**Comment by sinedied** [comment]
> Why not a pull request that adds what I suggested?

Because it will not work when different prefix are used for services (like `/api/v1` and `/api/v2`) which is the primary point of versioning 😉
