### ISSUE TITLE
Is there a version that works with OAS 2.0?

### ISSUE THREAD

**Issue by bhgames** [feathersjs/feathers-swagger#82]
Just wondering...is there a version of this that supports Swagger 2? I need to make a Python SDK using bravado(a python codegen tool based on OAS 2.0) and they don't plan to add 3.0 support.

**Comment by daffl** [comment]
What do you mean? The current version on npm supports Swagger UI 2.x

**Comment by bhgames** [comment]
Thanks for such a quick answer! This is what I mean: https://screencast.com/t/5m4QCTZsz It says 3.0 on your docs.

**Comment by bhgames** [comment]
Ah, is master here quite diverged fromt he latest published package?

**Comment by daffl** [comment]
Yes. You can find links to the trees of the published version at https://github.com/feathersjs/feathers-swagger/releases

**Comment by bhgames** [comment]
Okay, thank you!
