### ISSUE TITLE
Supported in Feathers 2?

### ISSUE THREAD

**Issue by wkw** [feathersjs/feathers-swagger#9]
Since [this](https://github.com/feathersjs/feathers/issues/24#issuecomment-198926010) is the only info I can find regarding Feathers 2 support for this package, I'm guessing it hasn't been updated for F2. 

Any additional information available regarding future plans for continuing this, or some specifics on what would need to get updated? I have to start generating Swagger docs more or less immediately, and deciding what path of least resistance is.

**Comment by daffl** [comment]
Did you get a chance to try if it works? Feathers 2 didn't change dramatically and from what I can tell everything this plugin is using still works the same. That comment was mostly talking about upgrading to the new plugin development infrastructure (including ES6 syntax) and possibly the latest Swagger format (not sure if it changed or if that's even necessary).

**Comment by wkw** [comment]
I have not tried it. I ran the example which was using something like feathers 1.0.2 (?). Though we've used Swagger for other projects, I was never the one creating the docs, so I'm gonna spend some time looking at the technology separately for now so I can better determine if I want, or see an advantage to mingling the extra info inside the api service handlers.
thanks for the response. And it will be helpful for anyone else wondering the same.

**Comment by thREam** [comment]
When I used feathers-swagger with feather 2, I follow the documentation to use, but when I visited the petstore.swagger.io and explore local docs, petstore.swagger.io console errors, and swagger is 2.x version.
Do you have any plans to update feathers-swagger? In addition, the feather 3 when released? Thank you, Have a nice day!

**Comment by josx** [comment]
:+1:
